Setting up the project
MohammedElseddik/Web-development-First-Capstone-Project pull request #1
Opened 2022-03-16 16:32 UTC by MohammedElseddik

## In this branch I : 
- created my first capstone project, the website is about remote jobs and how people can work remotely.
- created the home page and about page for mobile and desktop.
- Used a mobile-first approach to build the website and I also used a component-based design where I build the most important component to build another block of the website.
- Create the Featured section dynamically using Javascript.

### loom video link:
https://www.loom.com/share/091acb9fa02f4b1aa838e677ae2ae9bd

2022-03-16 19:06 UTC, prolajumokeoni requested changes
Hi @MohammedElseddik , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️ Good PR title and description
✔️ Good commit messages

## Required Changes ♻️

- [ ] Kindly ensure your video does not exceed 5 minutes, also when you showpiece of code you are proud of you can give reasons why you are proud of the piece of code👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

<br>
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 19:06 UTC, prolajumokeoni commented on main.js
> +    featuredSectionBoy.innerHTML += `<div class="speaker-container">
- [x] Kindly change the div tag wrapper for "speaker-container" to article tag, this will make your project more semantic and easily readable by browsers

2022-03-16 19:06 UTC, prolajumokeoni commented on main.js
> +              alt=""
- [x] Kindly add alt tag for images, it makes your website more accessible 👍🏿

2022-03-16 19:06 UTC, prolajumokeoni commented on index.html
> +    <section class="main-program">
## MOBILE
Behance Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/69638013/158666063-ee512967-7397-429b-9678-ba6553988e9e.png)  | ![left](https://user-images.githubusercontent.com/69638013/158667211-c033c8a2-b0a5-48a7-825d-a15b93da6970.png)
- [x] Please align all text of p tag "sub-progran__description"   to the left so it looks like the original design


<br>

Behance Design          |  Your design     
:-------------------------:|:-------------------------:
![gbng](https://user-images.githubusercontent.com/69638013/158664203-7fcc0ac8-eabf-4026-b7f4-d93ab30ad03e.png)  |  ![bg2](https://user-images.githubusercontent.com/69638013/158664176-4a796439-ad11-4cc6-83a3-553d726af60a.png)

- [x] Kindly make the background of each card transparent similar to the design for both mobile and desktop
- [x]  It would be better to make each card design look like the Behance design by adjusting the width, height, and padding 👍🏿 

## OPTIONAL

- [x] Kindly add the main background image of this section for both mobile and desktop

2022-03-16 19:06 UTC, prolajumokeoni commented on index.html
> +      <button class="btn btn--primary btn-block">Join the the course</button>
## MOBILE

Behance Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/69638013/158665210-f1ae6bd1-0da5-4a02-9fb0-d41372859bd8.png)  | ![aaa](https://user-images.githubusercontent.com/69638013/158665236-6e592a54-c0b4-47c0-8eb4-37d97ddf5943.png)

- [x] Kindly add the right padding to the button and it would be nice to add the font family so it looks similar to the original design

2022-03-16 20:51 UTC, MohammedElseddik commented on index.html
> +    <section class="main-program">
![Main deskio desktop](https://user-images.githubusercontent.com/97116942/158688206-21343a86-4d9f-46c5-9a7f-2ded7367b1f0.PNG)
@prolajumokeoni my design is similar for the Behance as the image that  I uploaded.
The background is not provided and I could not find similar one

2022-03-16 21:26 UTC, prolajumokeoni commented on index.html
> +    <section class="main-program">
> ![Main deskio desktop](https://user-images.githubusercontent.com/97116942/158688206-21343a86-4d9f-46c5-9a7f-2ded7367b1f0.PNG) @prolajumokeoni my design is similar for the Behance as the image that I uploaded. The background is not provided and I could not find similar one

Hi @MohammedElseddik from 768px this section looks a bit clustered, making this change would make your design look better from  768px

2022-03-17 13:34 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @MohammedElseddik, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
I like that you were using BEM naming convention in your class names 👍🏻 💯 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Clean UI design 💘 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 13:46 UTC, merged